using System.Text;
using System.Text.Json;
using NesEmulator.Core;
using NesEmulator.Core.Cartridges.Mappers;
using NesEmulator.Core.Cpu;
using NesEmulator.Core.Memory;

internal static class AccuracyRunner
{
    public static int Run(string[] args)
    {
        if (args.Length < 2 || args[0] is not ("--rom-suite" or "--dma-suite" or "--cpu-vectors"))
        {
            Console.Error.WriteLine("Usage: --rom-suite|--dma-suite <nes-test-roms directory> [report.md] [path filter] | --cpu-vectors <JSON directory>");
            return 2;
        }

        if (!Directory.Exists(args[1]))
        {
            Console.Error.WriteLine($"Directory does not exist: {args[1]}");
            return 2;
        }

        return args[0] == "--cpu-vectors" ? RunVectors(args[1]) : RunRoms(args);
    }

    private static int RunRoms(string[] args)
    {
        bool dma = args[0] == "--dma-suite";
        string[] suites = dma ? ["sprdma_and_dmc_dma"] : ["instr_test-v5/rom_singles", "instr_timing/rom_singles", "instr_misc/rom_singles",
            "cpu_dummy_writes", "cpu_interrupts_v2/rom_singles", "cpu_reset", "ppu_vbl_nmi/rom_singles",
            "apu_test/rom_singles", "mmc3_test_2/rom_singles"];
        List<string> paths = [];
        foreach (string suite in suites)
        {
            string directory = Path.Combine(args[1], suite);
            if (!Directory.Exists(directory))
            {
                Console.Error.WriteLine($"Missing suite: {suite}");
                return 2;
            }
            paths.AddRange(Directory.GetFiles(directory, "*.nes"));
        }
        paths.Sort(StringComparer.Ordinal);
        if (args.Length > 3)
            paths = paths.Where(p => p.Contains(args[3], StringComparison.OrdinalIgnoreCase)).ToList();
        if (paths.Count == 0) return 2;

        List<string> rows = ["# Accuracy ROM results", "",
            $"Generated by `dotnet run -c Release --project tests/NesEmulator.Tests -- {args[0]} roms/accuracy docs/{(dma ? "dma" : "accuracy")}-results.md`.", "",
            "The fetch script pins [nes-test-roms](https://github.com/christopherpow/nes-test-roms/tree/95d8f621ae55cee0d09b91519a8989ae0e64753b). Each row records the SHA-256 of the ROM actually tested.", "",
            "PASS requires the ROM's `$6000` result to be zero, with the `$6001–$6003` protocol signature present. Failures and timeouts remain failures; no screenshot is treated as a pass. Reset requests wait six frames before resetting the console.", "",
            dma ? "This additional suite measures DMC/OAM arbitration, including transfer length and copied sprite data. It is reported separately from the original 55-ROM baseline."
                : "The MMC3 tests require incompatible chip revisions: `6-MMC3_alt` explicitly selects the alternate MMC3A IRQ profile; the other MMC3 tests use the standard profile. The profile column records the configuration chosen before execution. ROM bytes are unchanged; the core does not detect test names.", "",
            "| Test ROM | IRQ profile | Result | ROM output | SHA-256 |", "|---|---|---|---|---|"];
        int failures = 0;
        foreach (string path in paths)
        {
            string name = Path.GetRelativePath(args[1], path).Replace('\\', '/');
            Mmc3IrqRevision revision = name == "mmc3_test_2/rom_singles/6-MMC3_alt.nes"
                ? Mmc3IrqRevision.Alternate : Mmc3IrqRevision.Standard;
            string profile = name.StartsWith("mmc3_test_2/", StringComparison.Ordinal)
                ? revision == Mmc3IrqRevision.Alternate ? "MMC3A (alternate)" : "MMC3 standard" : "—";
            string result;
            string message = "";
            try
            {
                Nes nes = Nes.FromFile(path, mmc3Revision: revision);
                result = "TIMEOUT";
                int resetAt = -1;
                // A finite emulated-time budget, independent of the host's speed.
                for (int frame = 0; frame < 3600; frame++)
                {
                    nes.RunFrame();
                    nes.Apu.DiscardSamples();
                    if (nes.Bus.Peek(0x6001) != 0xDE || nes.Bus.Peek(0x6002) != 0xB0 || nes.Bus.Peek(0x6003) != 0x61)
                        continue;
                    byte status = nes.Bus.Peek(0x6000);
                    if (status == 0x81)
                    {
                        if (resetAt < 0) resetAt = frame + 6;
                        if (frame == resetAt) nes.Reset();
                    }
                    else
                    {
                        resetAt = -1;
                        if (status < 0x80)
                        {
                            result = status == 0 ? "PASS" : $"FAIL ({status})";
                            break;
                        }
                    }
                }
                StringBuilder output = new();
                for (int address = 0x6004; address < 0x6800; address++)
                {
                    byte value = nes.Bus.Peek((ushort)address);
                    if (value == 0) break;
                    output.Append((char)value);
                }
                message = System.Text.RegularExpressions.Regex.Replace(output.ToString(), @"\x1B\[[0-9;]*m", "");
                message = System.Text.RegularExpressions.Regex.Replace(message, @"\s+", " ").Trim();
                if (result == "PASS") message = "Passed";
            }
            catch (Exception exception) when (exception is IOException or InvalidDataException or NotSupportedException)
            {
                result = "ERROR";
                message = exception.Message;
            }
            if (result != "PASS") failures++;
            Console.WriteLine($"{result,-10} {name} [{profile}]  {message}");
            string hash = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();
            rows.Add($"| {name} | {profile} | {result} | {message.Replace("|", "\\|")} | {hash} |");
        }
        rows.Add($"\n{paths.Count - failures}/{paths.Count} ROMs passed. Timeout: 3,600 emulated frames per ROM.");
        if (args.Length > 2) File.WriteAllLines(args[2], rows);
        Console.WriteLine(rows[^1]);
        return failures == 0 ? 0 : 1;
    }

    private static int RunVectors(string directory)
    {
        string[] files = Directory.GetFiles(directory, "*.json");
        Array.Sort(files, StringComparer.Ordinal);
        if (files.Length == 0) return 2;
        int total = 0, failures = 0;
        foreach (string file in files)
        {
            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(file));
            int failed = 0, count = 0;
            string first = "";
            VectorBus bus = new();
            foreach (JsonElement test in document.RootElement.EnumerateArray())
            {
                bus.Accesses.Clear();
                Array.Clear(bus.Memory);
                JsonElement initial = test.GetProperty("initial"), final = test.GetProperty("final");
                foreach (JsonElement cell in initial.GetProperty("ram").EnumerateArray())
                    bus.Memory[cell[0].GetInt32()] = cell[1].GetByte();
                Cpu6502 cpu = new(bus) { PC = initial.GetProperty("pc").GetUInt16(),
                    S = initial.GetProperty("s").GetByte(), A = initial.GetProperty("a").GetByte(),
                    X = initial.GetProperty("x").GetByte(), Y = initial.GetProperty("y").GetByte(),
                    P = initial.GetProperty("p").GetByte() };
                cpu.Step();
                var expected = test.GetProperty("cycles").EnumerateArray()
                    .Select(c => (c[0].GetUInt16(), c[1].GetByte(), c[2].GetString()!)).ToArray();
                // JAM never completes; the fixture records a finite prefix of its bus loop.
                while (cpu.Jammed && cpu.Cycles < expected.Length) cpu.Step();
                bool pass = cpu.PC == final.GetProperty("pc").GetUInt16() && cpu.S == final.GetProperty("s").GetByte()
                    && cpu.A == final.GetProperty("a").GetByte() && cpu.X == final.GetProperty("x").GetByte()
                    && cpu.Y == final.GetProperty("y").GetByte() && cpu.P == final.GetProperty("p").GetByte()
                    && cpu.Cycles == expected.Length && bus.Accesses.SequenceEqual(expected)
                    && final.GetProperty("ram").EnumerateArray().All(c => bus.Memory[c[0].GetInt32()] == c[1].GetByte());
                if (!pass)
                {
                    if (failed == 0) first = $"{test.GetProperty("name").GetString()}: actual {string.Join(",", bus.Accesses)}; expected {string.Join(",", expected)}; P={cpu.P:X2}/{final.GetProperty("p").GetByte():X2}";
                    failed++;
                }
                count++;
            }
            Console.WriteLine($"{Path.GetFileName(file)}: {count - failed}/{count} {first}");
            total += count;
            failures += failed;
        }
        Console.WriteLine($"{total - failures}/{total} vectors passed (registers, memory, and every bus cycle).");
        return failures == 0 ? 0 : 1;
    }

    private sealed class VectorBus : IBus
    {
        public byte[] Memory { get; } = new byte[65536];
        public List<(ushort, byte, string)> Accesses { get; } = [];
        public byte Read(ushort address) { byte value = Memory[address]; Accesses.Add((address, value, "read")); return value; }
        public void Write(ushort address, byte value) { Memory[address] = value; Accesses.Add((address, value, "write")); }
        public byte Peek(ushort address) => Memory[address];
    }
}
