using System.Security.Cryptography;
using System.Text;
using NesEmulator.Core;
using NesEmulator.Core.Input;

/// <summary>
/// Runs the complete AccuracyCoin collection, one test at a time, on an
/// unmodified ROM. The menu layout is read out of the ROM image itself, so the
/// test list, its order and each result address come from the cartridge rather
/// than from a table maintained here.
/// </summary>
internal static class CoinSuiteRunner
{
    private const string Revision = "9bc42d1e3acbeeaea215b1011d58f4ce72a8a49e";
    private const string RomHash = "7e25ac08d2e7ed14c9b1f16bd853148fef09a824452164f8e0d69fd2bd96176c";

    // The ROM's own tally ignores tests whose result byte lives on page 3:
    // those print information instead of judging the console.
    private const int InformationalPage = 3;
    private const int FrameBudget = 3600;

    private readonly record struct CoinTest(int Page, string PageName, int Index, string Name, ushort Result)
    {
        public bool Informational => Result >> 8 == InformationalPage;
    }

    public static int Run(string[] args)
    {
        string path = Path.Combine(args[1], "AccuracyCoin.nes");
        if (!File.Exists(path)) { Console.Error.WriteLine($"Missing ROM: {path}"); return 2; }
        byte[] image = File.ReadAllBytes(path);
        string hash = Convert.ToHexString(SHA256.HashData(image)).ToLowerInvariant();
        if (hash != RomHash)
        {
            Console.Error.WriteLine($"Expected the AccuracyCoin ROM from {Revision}; supplied ROM was left untouched.");
            return 2;
        }

        List<CoinTest> tests = Parse(image);
        if (args.Length > 3)
            tests = tests.Where(t => $"{t.PageName}/{t.Name}".Contains(args[3], StringComparison.OrdinalIgnoreCase)).ToList();
        if (tests.Count == 0) { Console.Error.WriteLine("No test matched the filter."); return 2; }

        List<string> rows = ["# AccuracyCoin full results", "",
            "Generated by `dotnet run -c Release --project tests/NesEmulator.Tests -- --coin-suite roms/accuracy-coin docs/accuracy-coin-results.md`.", "",
            $"Source: [AccuracyCoin at `{Revision[..7]}`](https://github.com/100thCoin/AccuracyCoin/tree/{Revision}). ROM SHA-256: `{hash}`.", "",
            "Every test in the collection, run individually on the unmodified ROM. The page list, test order and result addresses are parsed out of the ROM's own menu tables, so this report cannot drift from the cartridge. Each test starts from a fresh power-on, is selected with controller input, and is read only from the result slot the ROM itself writes. No CPU, RAM or ROM state is patched.", "",
            $"The ROM encodes a result as: bit 0 set is a pass, bit 0 clear with bit 1 set is a failure whose code is the remaining bits, `$FF` is a skipped test, `$03` is still running. A test that never leaves the running state within {FrameBudget:N0} emulated frames is reported as a timeout. Passing results may still carry a variant code, which the ROM displays as a sprite next to the tile.", "",
            "The five Power On State entries print information rather than judging the console; the ROM excludes them from its own tally and so does the total here.", "",
            "| Page | # | Test | Result | Raw | Code |", "|---|---:|---|---|---|---|"];

        int passed = 0, failed = 0, counted = 0, informational = 0;
        List<string> failures = [];
        foreach (CoinTest test in tests)
        {
            (string status, byte result) = RunOne(path, test);
            string code = status.StartsWith("FAIL", StringComparison.Ordinal) ? $"{result >> 2}"
                : result >> 2 != 0 && status == "PASS" ? $"variant {result >> 2}" : "—";
            if (test.Informational) informational++;
            else
            {
                counted++;
                if (status == "PASS") passed++;
                else { failed++; failures.Add($"{test.PageName} / {test.Name}: {status}"); }
            }
            Console.WriteLine($"{status,-10} [{test.Page:00}/{test.Index:00}] {test.PageName} / {test.Name}  ${result:X2}");
            rows.Add($"| {test.PageName} | {test.Index} | {test.Name.Replace("|", "\\|")} | {status} | ${result:X2} | {code} |");
        }

        rows.Add("");
        rows.Add($"{passed}/{counted} judged tests passed. {informational} informational entries are reported but not counted.");
        if (failures.Count > 0)
        {
            rows.Add("");
            rows.Add("## Outstanding failures");
            rows.Add("");
            foreach (string failure in failures) rows.Add($"- {failure}");
        }

        if (args.Length > 2 && args[2].Length > 0) File.WriteAllLines(args[2], rows);
        Console.WriteLine();
        Console.WriteLine(rows.First(r => r.Contains("judged tests passed", StringComparison.Ordinal)));
        return failed == 0 ? 0 : 1;
    }

    /// <summary>Boots the ROM, walks the menu to one test and reads its result slot.</summary>
    private static (string Status, byte Result) RunOne(string path, CoinTest test)
    {
        Nes nes = Nes.FromFile(path);
        void Frames(int count)
        {
            for (int i = 0; i < count; i++) { nes.RunFrame(); nes.Apu.DiscardSamples(); }
        }

        void Press(NesButton button)
        {
            nes.Port1.Buttons = button;
            Frames(2);
            nes.Port1.Buttons = 0;
            Frames(3);
        }

        Frames(120);
        for (int i = 0; i < test.Page; i++) Press(NesButton.Right);
        for (int i = 0; i <= test.Index; i++) Press(NesButton.Down);
        if (nes.Bus.Peek(0x14) != test.Page || nes.Bus.Peek(0x16) != test.Index) return ("MENU", 0);

        byte before = nes.Bus.Peek(test.Result);
        if (before == 0xFF) return ("SKIPPED", before);
        Press(NesButton.A);

        // Informational entries never write a verdict, so they are given a fixed
        // budget and reported as what they are rather than as a pass or a failure.
        if (test.Informational)
        {
            Frames(60);
            return ("INFO", nes.Bus.Peek(test.Result));
        }

        byte result = 0;
        for (int frame = 0; frame < FrameBudget; frame++)
        {
            Frames(1);
            result = nes.Bus.Peek(test.Result);
            if ((result & 3) is 1 or 2) break;
        }

        return ((result & 3) switch
        {
            1 => "PASS",
            2 => $"FAIL ({result >> 2})",
            _ => "TIMEOUT",
        }, result);
    }

    /// <summary>
    /// Walks the ROM's menu tables: a pointer list at $8100, then one page per
    /// pointer holding a title and `name, $FF, result word, routine word` entries.
    /// </summary>
    private static List<CoinTest> Parse(byte[] image)
    {
        byte[] prg = image[16..(16 + 32768)];
        byte At(int address) => prg[address - 0x8000];
        ushort Word(int address) => (ushort)(At(address) | (At(address + 1) << 8));

        int firstPage = Word(0x8100);
        int pages = (firstPage - 0x8100) / 2;
        List<CoinTest> tests = [];
        for (int page = 0; page < pages; page++)
        {
            int address = Word(0x8100 + 2 * page);
            StringBuilder title = new();
            while (At(address) != 0xFF) title.Append((char)At(address++));
            address++;

            for (int index = 0; At(address) != 0xFF; index++)
            {
                StringBuilder name = new();
                while (At(address) != 0xFF) name.Append((char)At(address++));
                address++;
                ushort result = Word(address);
                address += 4; // the result slot and the test routine
                tests.Add(new CoinTest(page, title.ToString(), index, name.ToString().Trim(), result));
            }
        }

        return tests;
    }
}
