using System.Security.Cryptography;
using NesEmulator.Core;
using NesEmulator.Core.Input;

internal static class DmaAbortRunner
{
    private const string Revision = "9bc42d1e3acbeeaea215b1011d58f4ce72a8a49e";
    private const string RomHash = "7e25ac08d2e7ed14c9b1f16bd853148fef09a824452164f8e0d69fd2bd96176c";

    public static int Run(string[] args)
    {
        string path = Path.Combine(args[1], "AccuracyCoin.nes");
        if (!File.Exists(path)) { Console.Error.WriteLine($"Missing ROM: {path}"); return 2; }
        string hash = Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();
        if (hash != RomHash) { Console.Error.WriteLine($"Expected the AccuracyCoin ROM from {Revision}; supplied ROM was left untouched."); return 2; }
        List<string> rows = ["# DMC DMA stop results", "",
            "Generated by `dotnet run -c Release --project tests/NesEmulator.Tests -- --dma-abort-suite roms/accuracy-coin docs/dma-stop-results.md`.", "",
            $"Source: [AccuracyCoin at `{Revision[..7]}`](https://github.com/100thCoin/AccuracyCoin/tree/{Revision}).",
            "Runs the unmodified AccuracyCoin ROM through controller input, selecting page 13's overlap and abort tests. No CPU, RAM or ROM state is patched. The ROM performs its own DMA synchronization prerequisite.", "",
            "The ROM's result byte is zero before a test, 3 while running, and has low bits 01 for PASS or 10 for FAIL. Upper bits encode a success variant or failure code. Implicit-abort success $05 identifies the late RP2A03G/H behavior; $09 identifies the earlier variant. Skips, timeouts and other values are not passes. Timeout: 3,600 frames per selected test.", "",
            $"ROM SHA-256: `{hash}`.", "",
            "| Test | Result | Raw result | Timing observations |", "|---|---|---|---|"];
        int passed = 0;
        foreach (var test in new[] { (7, 0x477, "DMC DMA + OAM DMA"), (8, 0x479, "Explicit DMA Abort"), (9, 0x478, "Implicit DMA Abort") })
        {
            Nes nes = Nes.FromFile(path);
            void Frames(int count) { for (int i = 0; i < count; i++) { nes.RunFrame(); nes.Apu.DiscardSamples(); } }
            void Press(NesButton button) { nes.Port1.Buttons = button; Frames(2); nes.Port1.Buttons = 0; Frames(3); }
            Frames(120);
            for (int i = 0; i < 12; i++) Press(NesButton.Right);
            for (int i = 0; i <= test.Item1; i++) Press(NesButton.Down);
            if (nes.Bus.Peek(0x14) != 12 || nes.Bus.Peek(0x16) != test.Item1)
            { Console.Error.WriteLine("AccuracyCoin did not reach the requested menu entry."); return 1; }
            if (nes.Bus.Peek((ushort)test.Item2) != 0)
            { Console.Error.WriteLine("AccuracyCoin result was not initially untested."); return 1; }
            Press(NesButton.A);
            byte result = 0;
            for (int frame = 0; frame < 3600; frame++)
            {
                Frames(1);
                result = nes.Bus.Peek((ushort)test.Item2);
                if ((result & 3) is 1 or 2) break;
            }
            string status = (result & 3) == 1 ? "PASS" : (result & 3) == 2 ? $"FAIL ({result >> 2})" : "TIMEOUT";
            if (status == "PASS") passed++;
            string Bytes(int start) => string.Join(" ", Enumerable.Range(start, 16).Select(a => nes.Bus.Peek((ushort)a).ToString("X2")));
            string observations = test.Item1 == 8 ? Bytes(0x50) : test.Item1 == 9 ? $"{Bytes(0x500)} / {Bytes(0x520)} / {Bytes(0x540)}" : "";
            rows.Add($"| {test.Item3} | {status} | ${result:X2} | {observations} |");
            Console.WriteLine($"{status}: {test.Item3}, ${result:X2}; {observations}");
        }
        rows.Add($"\n{passed}/3 selected tests passed; this is not the complete AccuracyCoin suite.");
        if (args.Length > 2) File.WriteAllLines(args[2], rows);
        return passed == 3 ? 0 : 1;
    }
}
